services:
  web:
    build: .
    container_name: crave_killer_web
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/crave_killer}
      NODE_ENV: production
    ports:
      - "5000:5000"

  bot:
    build: ./bot
    container_name: crave_killer_bot
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/crave_killer
      BOT_TOKEN: ${BOT_TOKEN}
    dns:
      - 8.8.8.8
      - 1.1.1.1